/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import aplicacion.Cliente;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class Menu_Clientes_UI extends javax.swing.JFrame {

    private Cliente cliente;
    private Log_in_UI ventanaAnterior;
    /**
     * Creates new form Menu_Clientes_UI
     */
    public Menu_Clientes_UI(Cliente pCliente,Log_in_UI logIn) {
        initComponents();
        setCliente(pCliente);
        ventanaAnterior = logIn;
        bienvenidoLabel.setText("Bienvenido " + cliente.getNombre());
        ImageIcon img = new ImageIcon("src/images/icon8-box-24.png");
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenidoLabel = new javax.swing.JLabel();
        paquetesButton = new javax.swing.JButton();
        prealertarButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        perfilButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Package Notifier");
        setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(32, 33, 36));

        bienvenidoLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(62, 140, 129));
        bienvenidoLabel.setText("Bienvenido");

        paquetesButton.setBackground(new java.awt.Color(64, 130, 137));
        paquetesButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        paquetesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-box-24.png"))); // NOI18N
        paquetesButton.setText("Mis paquetes");
        paquetesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paquetesButtonActionPerformed(evt);
            }
        });

        prealertarButton.setBackground(new java.awt.Color(64, 130, 137));
        prealertarButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        prealertarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-alarm-filled-24.png"))); // NOI18N
        prealertarButton.setText("Prealertar un paquete");
        prealertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prealertarButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(64, 130, 137));
        logOutButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-24.png"))); // NOI18N
        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        perfilButton.setBackground(new java.awt.Color(64, 130, 137));
        perfilButton.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        perfilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-24.png"))); // NOI18N
        perfilButton.setText("Perfil");
        perfilButton.setToolTipText("");
        perfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prealertarButton)
                    .addComponent(logOutButton)
                    .addComponent(paquetesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bienvenidoLabel)
                    .addComponent(perfilButton))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenidoLabel)
                .addGap(53, 53, 53)
                .addComponent(perfilButton)
                .addGap(52, 52, 52)
                .addComponent(paquetesButton)
                .addGap(52, 52, 52)
                .addComponent(prealertarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(62, 140, 129));

        jLabel1.setBackground(new java.awt.Color(68, 107, 158));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-contacts-250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilButtonActionPerformed
        PerfilUsuarioUI perfil = new PerfilUsuarioUI(getCliente());
        perfil.setVisible(true);
    }//GEN-LAST:event_perfilButtonActionPerformed

    private void paquetesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paquetesButtonActionPerformed
        PaquetesUI paquetes = new PaquetesUI(getCliente());
        paquetes.setVisible(true);
    }//GEN-LAST:event_paquetesButtonActionPerformed

    private void prealertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prealertarButtonActionPerformed
        PrealertarUI prealertar = new PrealertarUI(cliente);
        prealertar.setVisible(true);
    }//GEN-LAST:event_prealertarButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        setVisible(false);
        ventanaAnterior.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton paquetesButton;
    private javax.swing.JButton perfilButton;
    private javax.swing.JButton prealertarButton;
    // End of variables declaration//GEN-END:variables
}
